name: Super-Linter

on: workflow_dispatch
permissions:
  statuses: write  # Required for Status API

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
